version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5001:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
